# SQLite version 3.x
#   gem install pg
#
#   Ensure the pg gem is defined in your Gemfile
#   gem 'pg'
#

development:
  adapter: postgresql
  encoding: unicode
  database: wvc_app_development
  host: localhost
  pool: 5
  username: wvc_app
  password: black@123

test:
  adapter: postgresql
  encoding: unicode
  database: wvc_app_test
  host: localhost
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: wvc_app_production
  host: localhost
  pool: 5
  username: wvc_app
  password: